### PR TITLE
Improved matching regexp

### PR DESCRIPTION
**Pull request by FDiskas**
Improved matching regexp. 
Here is some tests: http://jsbin.com/yotazokeda/edit?js,console

### CODE REVIEW

**Comment by FDiskas** [comment]
Ok Ok - see that tests fails.

**Comment by jonkemp** [comment]
Tests are failing. Please fix failing tests.

**Comment by FDiskas** [comment]
This should work with the [symfony2 assetic](http://symfony.com/doc/current/cookbook/assetic/asset_management.html) and [laravel asset](https://laravel.com/docs/5.1/helpers#method-asset) and [elixir](https://laravel.com/docs/5.2/elixir#versioning-and-cache-busting) links in twig or blade or html or php.
```html
<script src="{{ asset('js/script.js') }}"></script>
<script type="text/javascript" src="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600"></script>
<script src="{{ asset('/assets/vendor/jquery/dist/jquery.js') }}"></script>
<script src='/assets/vendor/bootstrap-sass/assets/javascripts/bootstrap.js?Sdsd'></script>
<script src="{{ elixir('js/scripts.js') }}"></script>
```
Please merge :)

**Comment by FDiskas** [comment]
Added test cases "should support symfony2 twig and laravel5 blade assets"

**Comment by FDiskas** [comment]
With this pull request now it will be possible to combine two modules "wiredep" and "useref"
For example using laravel5 the gulp file will look something like
```js
require('laravel-elixir');
require('laravel-elixir-wiredep');

var options = {
	fileTypes: {
		php: {
			block: /(([ \t]*)<!--\s*bower:*(\S*)\s*-->)(\n|\r|.)*?(<!--\s*endbower\s*-->)/gi,
			detect: {
				js: /<script.*src=['"]([^'"]+)/gi,
				css: /<link.*href=['"]([^'"]+)/gi
			},
			replace: {
				js: '<script src="{{ asset(\'{{filePath}}\') }}"></script>',
				css: '<link rel="stylesheet" href="{{ asset(\'{{filePath}}\') }}" />'
			}
		}
	}
};

elixir(function (mix) {
	mix.wiredep('php', {src: 'welcome.blade.php'}, options).useref().version(['js/vendors.min.js', 'css/vendors.min.css']);
});
```
And the `welcome.blade.php` file
```twig
    @if ( Config::get('app.debug') )
        <!-- build:js(public) js/vendors.min.js -->
        <!-- bower:js -->
        <script src="{{ asset('/assets/vendor/jquery/dist/jquery.js') }}"></script>
        <script src="{{ asset('/assets/vendor/bootstrap-sass/assets/javascripts/bootstrap.js') }}"></script>
        <script src="{{ asset('/assets/vendor/bootstrap-select-sass/dist/js/bootstrap-select.js') }}"></script>
        <!-- endbower -->
        <script src="{{ asset('js/scripts.js') }}"></script>
        <!-- endbuild -->
    @else
        <script src="{{ elixir('js/scripts.min.js') }}"></script>
    @endif
...
```

**Comment by FDiskas** [comment]
Here is regexp rezults http://regexr.com/3d1m7

**Comment by FDiskas** [comment]
Anny news?

**Comment by jonkemp** [comment]
I'm ok with the tests but I would rather the values you want not be hardcoded. What happens if someone else wants something different? It would seem this would be something easily accomplished with regex.

**Comment by FDiskas** [comment]
I removed all hardcoded symbols.

**Comment by jonkemp** [comment]
Looks good. I prefer that. Can you please squash commits?

**Comment by FDiskas** [comment]
Sorry - its imposible for me using windows
```
git rebase -i HEAD~20
error: Your local changes to the following files would be overwritten by merge:
        test/testfiles/16-win-expected.html
        test/testfiles/16-win.html
Please, commit your changes or stash them before you can merge.
Aborting
```
Somehow files always got modified. I tried reverting them, committing them. Always got the same error.

**Comment by FDiskas** [comment]
Oh yeah :D I did it. Squashed commits to one :)

**Comment by jonkemp** [comment]
I don't see any reason why it wouldn't, but I want to make sure this still works with gulp-useref before accepting. I'll take a look. Thanks!

**Pull request merged**
